## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [35]:
# imports, no need to edit

import numpy as np
import time
from numpy import random
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is a 1-dimensional array and a matrix is a 2-dimensional array in NumPy.

2. Construct a NumPy Array from a list of 10 elements.

In [36]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [37]:
arr = np.zeros((10,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [38]:
arr = np.ones((10,10), dtype=float)
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [39]:
arr = np.full((10,10), 9, dtype=int)
print(arr)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [40]:
vector = np.arange(start = 5, stop = 25, step = 3)
print(vector)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [41]:
arr = np.linspace(-1, 1, 30)
print(arr)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [42]:
arr = np.arange(start = 0, stop = 30).reshape(5,6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [43]:
arr = np.random.randint(50, size = 30)
print(np.sort(arr))

[ 1  1  2  7 10 10 11 14 18 20 20 21 21 22 23 23 23 24 28 29 32 35 37 38
 38 39 42 43 43 48]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [44]:
arr = np.ones((5,10))
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
50
(5, 10)
float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [45]:
arr = np.random.randint(10, size = (3,4,7))
print(arr)

[[[9 2 6 3 8 2 4]
  [2 6 4 8 6 1 3]
  [8 1 9 8 9 4 1]
  [3 6 7 2 0 3 1]]

 [[7 3 1 5 5 9 3]
  [5 1 9 1 9 3 7]
  [6 8 7 4 1 4 7]
  [9 8 8 0 8 6 8]]

 [[7 0 7 7 2 0 7]
  [2 2 0 4 9 6 9]
  [8 6 8 7 1 0 6]
  [6 7 4 2 7 5 2]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [46]:
arr = np.random.randint(0, 50, 20)
x = np.reshape(arr, (4,5))
print(x)

[[ 0 34 36 46 13]
 [ 2  0  4 25 13]
 [38 26  8 14 14]
 [25 41 12 31 38]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [47]:
arr = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.array([5,6])
arr4 = np.array([7,8])
x = np.concatenate((arr, arr2, arr3, arr4))
print(x)

[1 2 3 4 5 6 7 8]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [48]:
vector = np.array([1,2,3]).reshape(3,1)
matrix = np.array([[4,5,6], [7,8,9], [10,11,12]])

x = np.hstack((vector, matrix))
# x = np.concatenate((vector, matrix), axis=1)
print(x)

[[ 1  4  5  6]
 [ 2  7  8  9]
 [ 3 10 11 12]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

'axis = 0' is the other name of 'row', 'axis = 1' is the other name of 'column'

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [49]:
arr = np.random.randint(0, 30, 20)
x = [2,4,6]
print(arr[x])

[28 29 22]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [50]:
vector = np.random.rand(10)

vector[3] = 88

print(vector)

[ 0.62435405  0.29563369  0.10549426 88.          0.21844044  0.41650995
  0.88328026  0.32434502  0.12208795  0.35629784]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


Diagonal Matrix:
A square matrix in which all the non-diagonal elements are zero is called a diagonal matrix. The diagonal elements of a diagonal matrix are the elements that are present in the main diagonal of the matrix.

Trace Matrix:
Trace of a matrix is the sum of the diagonal elements of a square matrix. It is also known as the diagonal sum of a matrix. The trace of a matrix is represented by the symbol Tr or tr(A). It is only applicable to square matrices.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [51]:
arr = [1,2,3,4,5]
dia = np.diag(arr)

print(dia)

for index, value in np.ndenumerate(dia):
    print(f"Value {value} is located at index {index}")
    
    
# indexes = np.where(dia != 0)
# print(indexes)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Value 1 is located at index (0, 0)
Value 0 is located at index (0, 1)
Value 0 is located at index (0, 2)
Value 0 is located at index (0, 3)
Value 0 is located at index (0, 4)
Value 0 is located at index (1, 0)
Value 2 is located at index (1, 1)
Value 0 is located at index (1, 2)
Value 0 is located at index (1, 3)
Value 0 is located at index (1, 4)
Value 0 is located at index (2, 0)
Value 0 is located at index (2, 1)
Value 3 is located at index (2, 2)
Value 0 is located at index (2, 3)
Value 0 is located at index (2, 4)
Value 0 is located at index (3, 0)
Value 0 is located at index (3, 1)
Value 0 is located at index (3, 2)
Value 4 is located at index (3, 3)
Value 0 is located at index (3, 4)
Value 0 is located at index (4, 0)
Value 0 is located at index (4, 1)
Value 0 is located at index (4, 2)
Value 0 is located at index (4, 3)
Value 5 is located at index (4, 4)


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [52]:
vector = np.arange(start = 10, stop = 21)
print(vector)

print(vector[2:])

[10 11 12 13 14 15 16 17 18 19 20]
[12 13 14 15 16 17 18 19 20]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [53]:
matrix = np.random.rand(10,10)
print(matrix, '\n')

print(matrix[2,4], '\n')

print(matrix[ : , 4], '\n')

print(matrix[1, : ], '\n')

print(matrix[1:7, : ], '\n')

print(matrix[2:6, : 4:8 ], '\n')

print(matrix[5:, :4 ], '\n')

x = matrix[4:4] = 1995
print(x)

[[9.06828442e-01 2.72132249e-01 6.47690121e-01 5.20376995e-04
  3.52568856e-01 3.04781258e-01 1.64655853e-01 5.34089419e-01
  4.84829971e-01 6.92436033e-01]
 [2.69412334e-01 2.44125522e-01 1.68291042e-01 2.18764220e-01
  5.58102002e-01 4.03836171e-01 6.48922471e-02 2.53915414e-01
  2.46876063e-01 6.96304273e-01]
 [7.12270590e-01 1.48086930e-01 9.97740485e-01 2.66781014e-01
  9.76614956e-01 4.11037013e-01 3.30507329e-02 3.45071248e-01
  6.34351345e-01 6.80705452e-01]
 [5.30934583e-01 4.47783165e-01 5.52893089e-01 5.92696724e-01
  8.08533263e-02 3.69654456e-01 2.42159938e-01 8.03139756e-01
  4.70300634e-01 9.83423141e-01]
 [3.98824442e-01 8.16431873e-01 7.98345125e-01 1.50717544e-01
  5.08198777e-01 6.95812807e-01 8.58358805e-01 3.25958905e-01
  2.20241048e-01 7.11149532e-01]
 [8.09501046e-01 3.48665987e-01 9.61765511e-02 9.40523264e-01
  3.97572021e-01 5.17751351e-01 8.37710106e-01 6.75690117e-01
  7.35216119e-01 2.09071621e-01]
 [5.41447974e-01 6.95784399e-01 2.28550022e-01 1.74954927e

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [54]:
arr = np.arange(start = 0, stop = 51, step = 5)
print(arr)

print(arr[arr>20], '\n')

print(arr[arr<30], '\n')

count = np.count_nonzero(arr == 33)
print(count, '\n')

x = arr * 5
print(x)


[ 0  5 10 15 20 25 30 35 40 45 50]
[25 30 35 40 45 50] 

[ 0  5 10 15 20 25] 

0 

[  0  25  50  75 100 125 150 175 200 225 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [55]:
arr = np.random.rand(50)
print(arr, '\n')

print(np.mean(arr), '\n')

print(np.std(arr), '\n')

print(np.var(arr), '\n')

print(np.median(arr), '\n')

print(np.min(arr), '\n')

print(np.max(arr))


[0.50881408 0.63633262 0.25046182 0.58987085 0.97889286 0.48674215
 0.90609879 0.43439437 0.35007841 0.64510336 0.66892406 0.86416757
 0.23018527 0.49919338 0.5720042  0.76855401 0.04360377 0.99455051
 0.46994451 0.27956034 0.88349402 0.74771877 0.95307185 0.3307503
 0.55276497 0.57229247 0.98033158 0.07534626 0.30569702 0.19091103
 0.26847486 0.48527987 0.37268687 0.39469147 0.84421314 0.93001683
 0.07041613 0.20891872 0.67114352 0.35864678 0.25416365 0.29529059
 0.32255076 0.84866979 0.13662133 0.708911   0.55281998 0.29651014
 0.41978086 0.25620694] 

0.5093173685382544 

0.2675625278204558 

0.0715897062936722 

0.4860110136178854 

0.04360377175443375 

0.994550510797341


24. What are the differences between Pandas Series and NumPy arrays?

YOUR ANSWER HERE

25. Create a 5-element series with different data types, with an index of capital letters.

In [56]:
data = {
    'A': [1,2, 'Kamil'],
    'B': [3,4, 'Safo'],
    'C': [5,6, 'Keko'],
    'D': [7,8, 'Seko'],
    'E': [9,10, 'Tefo']
}

df = pd.DataFrame(data)

print(df, '\n')

s = pd.Series(df.loc[2])
print(s)

       A     B     C     D     E
0      1     3     5     7     9
1      2     4     6     8    10
2  Kamil  Safo  Keko  Seko  Tefo 

A    Kamil
B     Safo
C     Keko
D     Seko
E     Tefo
Name: 2, dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [57]:
data = {
    'France': ['Paris'],
    'Turkey': ['Angara'],
    'Netherlands': ['Amsterdam'],
    'Germany': ['Berlin'],
    'Belgium': ['Brussels']
} 

df = pd.DataFrame(data)

print(df, '\n')

x = pd.Series(data.values(), index=data.keys())
print(x)

  France  Turkey Netherlands Germany   Belgium
0  Paris  Angara   Amsterdam  Berlin  Brussels 

France             [Paris]
Turkey            [Angara]
Netherlands    [Amsterdam]
Germany           [Berlin]
Belgium         [Brussels]
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [58]:
vector = np.random.rand(10)
print(vector)

series = pd.Series(vector, index = list('abcdefghij'))
print(series, '\n')

print(series['c'], '\n')

print(series[0], '\n')

print(series['b'], series['g'])

[0.61151371 0.08159418 0.00518486 0.62789441 0.19427395 0.07094092
 0.39678383 0.05076853 0.88661715 0.02761677]
a    0.611514
b    0.081594
c    0.005185
d    0.627894
e    0.194274
f    0.070941
g    0.396784
h    0.050769
i    0.886617
j    0.027617
dtype: float64 

0.005184862773986776 

0.6115137108656805 

0.08159418040024036 0.3967838272138884


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [59]:
serie1 = pd.Series([1,2,3,4,5])
serie2 = pd.Series(['a', 'b', 'c', 'd', 'e'])


df = pd.concat([serie1, serie2], axis=0)
print(df)

ind = pd.Index(df)
print(ind)

0    1
1    2
2    3
3    4
4    5
0    a
1    b
2    c
3    d
4    e
dtype: object
Index([1, 2, 3, 4, 5, 'a', 'b', 'c', 'd', 'e'], dtype='object')


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [70]:
start_time = time.time()

cycles = 0

while True:
    difference = np.random.rand(20, 20) - np.random.rand(20, 20) 
    
    diag = abs(np.diag(difference))
    
    if (diag <= 0.1).all():
        end_time = time.time()
        print("Desired matrix found at this cycle: ", cycles, '\n')
        print("It took: ", end_time - start_time, "seconds.", '\n')
        print("Desired matrix: ", '\n')
        print(difference)
        break
    cycles += 1


Desired matrix found at this cycle:  551852 

It took:  12.148749828338623 seconds. 

Desired matrix:  

[[ 9.62850883e-02  1.41050533e-01 -9.45192285e-02 -5.09998621e-01
  -3.70454790e-01  1.92359767e-01  3.67482006e-01  4.18821688e-01]
 [ 3.19500032e-01  1.07714627e-02  7.22883453e-01  3.81354269e-01
  -1.71174016e-01  5.56973048e-01 -1.67324129e-02  4.32238400e-02]
 [-9.32322205e-02  3.92030318e-01  4.47309719e-02  6.53511809e-01
  -2.90995933e-01  1.22392792e-01 -1.15194622e-01  2.95910905e-01]
 [-1.28642342e-01 -1.35695446e-01  3.60499119e-01  4.65806376e-02
   6.66176114e-02 -5.17508316e-02 -4.49993556e-02 -9.12314516e-02]
 [ 4.21329148e-01  8.24865996e-01 -5.66380785e-01  5.36974836e-01
  -9.38794366e-04 -3.57214820e-01 -3.75203581e-01 -3.35668969e-01]
 [ 1.98415844e-01  4.14403471e-01  6.78453777e-01  2.15622973e-01
  -1.54635909e-02 -9.86843353e-03  6.37233608e-01  2.63854843e-01]
 [ 4.14294394e-01 -2.01788269e-01  4.46025670e-01  2.26164475e-01
   4.70720407e-01  2.32694980e-