## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [3]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

 A vector is an array with a single dimension (there's no difference between row and column vectors), while a matrix refers to an array with two dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [6]:
x = np.zeros((10,10), dtype=int)
x


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [8]:
x = np.ones((10,10), dtype=float)
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [10]:
x = np.full((10,10), 9, dtype=int)
x

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [29]:
x = np.arange(5,25,3)
x


array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [33]:
x = np.linspace(-1, 1, 30)
x

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [68]:

# x = np.arange(31).reshape((5, 6))
x  = np.arange(6).reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

9. Create an array of 30 random integers and sort it in ascending order.

In [76]:
x = np.random.randint(100, size= 30)
x.sort()
x


array([ 0,  1, 10, 15, 16, 18, 23, 31, 31, 37, 43, 52, 54, 55, 58, 67, 68,
       69, 69, 69, 72, 74, 79, 85, 89, 92, 95, 96, 96, 97])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [83]:
x = np.ones((5,10))
print(f'''matrix: {x}
number of elements: {x.size}
shape of matrix: {x.shape}
data type: {x.dtype}

 ''')


matrix: [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
number of elements: 50
shape of matrix: (5, 10)
data type: float64

 


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [87]:
x = np.random.randint(0,10 , size = (3,4,7))
x

array([[[6, 3, 5, 3, 2, 6, 7],
        [3, 1, 9, 2, 0, 7, 2],
        [9, 6, 9, 4, 9, 4, 6],
        [8, 4, 0, 9, 9, 0, 1]],

       [[5, 8, 7, 4, 0, 6, 4],
        [5, 6, 2, 9, 2, 4, 5],
        [8, 4, 0, 3, 4, 9, 9],
        [4, 6, 3, 0, 4, 6, 9]],

       [[9, 5, 4, 3, 1, 3, 9],
        [9, 2, 9, 0, 7, 4, 3],
        [7, 6, 1, 0, 3, 7, 1],
        [2, 0, 0, 2, 4, 2, 0]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [7]:
x = np.random.randint(0,100, 20).reshape((4,5))
x

array([[71, 60, 20, 82, 86],
       [74, 74, 87, 99, 23],
       [ 2, 21, 52,  1, 87],
       [29, 37,  1, 63, 59]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [10]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.array([5,6])
arr4 = np.array([7,8])
arr = np.concatenate((arr1, arr2, arr3, arr4))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [27]:
vector = np.random.rand(3,1)
matrix = np.random.rand(3,3)
combine = np.hstack((vector, matrix))
combine

array([[0.63755747, 0.11959425, 0.71324479, 0.76078505],
       [0.88721274, 0.5612772 , 0.77096718, 0.4937956 ],
       [0.47221493, 0.52273283, 0.42754102, 0.02541913]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [31]:
arr = np.random.randint(100, size = 20)
arr
print(f'3rd element: {arr[2]} , 5rd element: {arr[4]} ,7rd element: {arr[6]} ')

3rd element: 1 , 5rd element: 55 ,7rd element: 58 


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [33]:
arr = np.random.randint(100, size = 10)
arr[3] = 1000
arr

array([  68,   97,   69, 1000,   10,   15,   96,   72,   58,   69])

18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


*diagonal matrix*
A square matrix in which every element except the principal diagonal elements is zero is called a Diagonal Matrix.

*trace matrix*
In a square matrix, the sum of elements of the principal diagonal is called the 'trace of a matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [34]:
arr =  np.random.randint(10, size = (5,5))
arr
#The indexes of the diagonal are (0,0), (1,1), (2,2), (3,3), (4,4)
#The elements of the diagonal are 2,2,7,8,9

array([[2, 3, 3, 2, 9],
       [2, 2, 3, 6, 3],
       [8, 0, 7, 6, 1],
       [7, 0, 8, 8, 1],
       [6, 9, 2, 6, 9]])

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [36]:
vec = np.arange(10,20)
print(f'3rd index: {vec[4]} , last index{vec[-1]}')

3rd index: 14 , last index19


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [39]:
arr =  np.random.randint(100, size = (10,10))
arr


array([[95, 47, 88,  0, 15, 60, 63, 62, 68, 21],
       [92, 66, 75, 25, 15, 50, 85, 56, 28, 77],
       [91, 68, 46, 93, 61, 68, 75, 15, 89, 89],
       [47, 84, 38, 99, 32, 93, 22,  9, 68, 99],
       [33, 51, 94,  9, 18, 57, 95,  0, 68,  3],
       [15, 23, 79,  1, 91, 31, 90, 83, 23, 11],
       [49, 34, 32, 32, 60, 50, 42, 11, 66, 64],
       [32, 39, 73, 42, 43, 28, 12, 11, 94, 45],
       [ 1, 34, 86, 80, 89,  7, 92, 25, 73, 89],
       [33,  6, 67, 57, 74, 28, 35, 88, 20, 35]])

In [53]:
arr[2,4]
arr[:,4]
arr[1,:]
arr[1:6, :]
arr[1:4,2:6]
arr[4,3]
arr[4,4] = 1982


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [56]:
arr = np.arange(0,51, 5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [61]:
arr[arr>20]
arr[arr<30]
arr[arr ==30]
arr*5


array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250])

23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [70]:
arr = np.random.rand(50)
print(f'''
standard deviation: {arr.std()}
variance: {arr.var()}
median: {np.median(arr)}
smallest value: {arr.max()}
largest value: {arr.min()}

''')


standard deviation: 0.32680876281328336
variance: 0.1068039674515489
median: 0.5561292670685629
smallest value: 0.9929647961193003
largest value: 0.011353644767419069




24. What are the differences between Pandas Series and NumPy arrays?

Pandas Series and NumPy arrays are both used for storing and manipulating data in Python, but they have some key differences.

Indexing: Pandas Series have an explicit index, which means that each element in a Series has a label that can be used for referencing and selecting specific elements. NumPy arrays, on the other hand, use integer-based indexing, where each element is referenced by its integer position in the array.

Data Types: NumPy arrays can only store elements of the same data type (e.g. all integers or all floats), while Pandas Series can store elements of different data types.

25. Create a 5-element series with different data types, with an index of capital letters.

In [71]:
data = {'A': 1, 'B': 'Fenyx', 'C': 1.2, 'D': [1, 2, 3], 'E': True}
s = pd.Series(data)
s

A            1
B        Fenyx
C          1.2
D    [1, 2, 3]
E         True
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [73]:
data = {"Nederland": "Amsterdam", "India": "New Delhi", "Uganda": "Kampala", "Spain": "Madrid", "Kazakhstan": "Astana"}
s = pd.Series(data)
s

Nederland     Amsterdam
India         New Delhi
Uganda          Kampala
Spain            Madrid
Kazakhstan       Astana
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [85]:
s = pd.Series(np.random.randn(10), index = ['a','b','c','d','e','f','g','h','i','j'])
s['c']
s[0]
print(s['b'], s['g'])


-0.9045418837870712 -0.773224970452823


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [88]:
ser1 = pd.Series(['A', 'B', 'C','D','E'])
ser2 = pd.Series(['F', 'G', 'H', 'I', 'J'])
concate = pd.concat([ser1, ser2], ignore_index= True)
concate.index = range(1,11)
concate

1     A
2     B
3     C
4     D
5     E
6     F
7     G
8     H
9     I
10    J
dtype: object

**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [ ]:
import time

start = time.time()

cycle = 0

while True:
    matrix1 = np.random.rand(20,20)
    matrix2 = np.random.rand(20,20)

    diff_matrix = matrix1 - matrix2

    
    if any(-0.1 <= diff_matrix.diagonal()[i] <= 0.1 for i in range(20)):
        break
    cycle += 1

end = time.time()
print("Number of cycles: ", cycle)
print("Time taken: ", end - start)
print("Desired matrix: \n", diff_matrix)
