## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [2]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

YOUR ANSWER HERE
A vector is an array with a single dimension, a matrix refers to an array with two dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [12]:
# YOUR CODE HERE
array = np.zeros((10, 10), dtype= 'i')
print(array)
print('\n', array.dtype)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
int32


4. Construct a 10x10 matrix filled with '1's, data type float.

In [15]:
# YOUR CODE HERE
array = np.ones((10, 10))
print(array)
print('\n', array.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float64


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [17]:
# YOUR CODE HERE
array = np.ones((10,10), dtype='i') * 9
print(array)
print('\n', array.dtype)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]
int32


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [23]:
# YOUR CODE HERE
array = np.arange(5, 25, 3)
print(array)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [24]:
# YOUR CODE HERE
array = np.linspace(-1, 1, num = 30)
print(array)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [28]:
# YOUR CODE HERE
array = np.arange(0, 30).reshape(5, 6)
print(array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [40]:
# YOUR CODE HERE
from numpy import random

array = np.random.randint(100, size = (30))
array = np.sort(array)
print(array)

[ 2  8 17 18 19 23 23 24 31 32 34 35 37 40 47 53 53 60 65 71 74 79 79 81
 83 88 92 98 98 98]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [151]:
# YOUR CODE HERE
array = np.ones((5,10))
print(array)
print('\n', array.size)
print('\n', array.shape)
print('\n', array.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 50

 (5, 10)

 float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [46]:
# YOUR CODE HERE
array = np.random.randint(10, size = (3, 4, 7))
print(array)

[[[3 0 3 0 4 3 7]
  [7 6 2 0 0 2 5]
  [6 5 5 5 2 5 7]
  [1 4 0 0 4 2 3]]

 [[2 0 0 4 5 2 8]
  [4 7 0 4 2 0 3]
  [4 6 0 2 1 8 9]
  [5 9 2 7 7 1 5]]

 [[6 1 9 1 9 0 7]
  [0 8 5 6 9 6 9]
  [2 1 8 7 9 6 8]
  [3 3 0 7 2 6 1]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [47]:
# YOUR CODE HERE
array = np.random.randint(100, size = 20).reshape((4, 5))
print(array)

[[65 31 86 62 85]
 [50 24 57 62 61]
 [21 57 57 85 48]
 [51 41 69 14 53]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [49]:
# YOUR CODE HERE
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
d = np.array([7, 8])
array = np.concatenate((a, b, c, d))
print(array)

[1 2 3 4 5 6 7 8]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [54]:
# YOUR CODE HERE
vector = np.array([0, 1, 2])
matrix = np.array([[3, 4, 5], [6, 7, 8], [9, 10, 11]])
# vector = vector.reshape(1, 3)
vector = vector.reshape(3, 1)
print(vector + matrix)

[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

YOUR CODE HERE
axis = 1 refers to columns, axis = 0 refers to rows.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [150]:
# YOUR CODE HERE
array = np.random.randint(100, size = (20))
print(array)
print('\n', array[3])
print('\n', array[5])
print('\n', array[7])

[94 10 23 67 78 59 63 31 32 89 96 86 15 95 10 19 52 89 40 53]

 67

 59

 31


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [149]:
# YOUR CODE HERE
array = np.random.randint(100, size= (10))
print(array)
array[3] = 45
print('\n', array)

[11  8 10 45 24 89 61 99 47 59]

 [11  8 10 45 24 89 61 99 47 59]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


YOUR ANSWER HERE
A diagonal matrix is a matrix (usually a square matrix of order n) filled with values on the main diagonal and zeros everywhere else. And trace of matrix is the sum of main diagonal elements of the matrix. 

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [134]:
# YOUR CODE HERE
a = [1, 2, 3, 4, 5]
array = np.diag(a)
print(array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [79]:
# YOUR CODE HERE
array = np.arange(10,20)
print(array)
print('\n', array[3:])

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17 18 19]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [89]:
# YOUR CODE HERE
array = np.random.randint(100, size = (10,10))
print(array)
print('\n', array[2, 4])
print('\n', array[:, 4])
print('\n', array[1, :])
print('\n', array[2:7, :])
print('\n', array[5:, :4])
array[5,5] = 1997
print('\n', array)

[[22 12 50 13 88 59 59 94 93 80]
 [87 61 28 74 38 69 22  8 94 27]
 [24 70 65 46 10 42 71 64  7 81]
 [32 12 96 40  9 64 12 88 85 10]
 [32 26 48 55 36 16  3 27 97 12]
 [14 72 23  4 43 96  6 66  5 76]
 [51 12 49  6 85 21 34 94 38 74]
 [98 46 95 45 69 60 77 50 20 90]
 [ 6 22 51 59 28 70 33 27 45  4]
 [91 15 36  1 19 76  7 10 51  9]]
[[  22   12   50   13   88   59   59   94   93   80]
 [  87   61   28   74   38   69   22    8   94   27]
 [  24   70   65   46   10   42   71   64    7   81]
 [  32   12   96   40    9   64   12   88   85   10]
 [  32   26   48   55   36   16    3   27   97   12]
 [  14   72   23    4   43 1997    6   66    5   76]
 [  51   12   49    6   85   21   34   94   38   74]
 [  98   46   95   45   69   60   77   50   20   90]
 [   6   22   51   59   28   70   33   27   45    4]
 [  91   15   36    1   19   76    7   10   51    9]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [148]:
# YOUR CODE HERE
array = np.arange(0,50,5)
print(array)
print('\n', array[array > 20])
print('\n', array[array < 30])
print('\n', np.sum(array)/ 33)
print('\n', array * 5)

[ 0  5 10 15 20 25 30 35 40 45]

 [25 30 35 40 45]

 [ 0  5 10 15 20 25]

 6.818181818181818

 [  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [147]:
# YOUR CODE HERE
array = np.random.rand(50)
print(array)
print('\n', array.std())
print('\n', array.var())
print('\n', array.mean())
print('\n', array.min())
print('\n', array.max())


[0.33462505 0.20104344 0.48038712 0.83029469 0.07350609 0.22028168
 0.74104664 0.84520319 0.51677482 0.04985868 0.42144156 0.31549508
 0.47646066 0.65298075 0.09364718 0.77989305 0.88604936 0.67374626
 0.53790014 0.06675827 0.88188375 0.41715154 0.94775997 0.17261188
 0.49606658 0.43147047 0.49566428 0.10343358 0.57272353 0.83569695
 0.81329468 0.42946563 0.92934421 0.78246972 0.72879854 0.7744183
 0.39658158 0.83009891 0.61144175 0.90700001 0.33408381 0.63203765
 0.11782295 0.84475983 0.35710309 0.95483468 0.78181332 0.14594085
 0.8661954  0.23400992]

 0.28072818578364567

 0.07880831429337708

 0.5404674218254859

 0.0498586793673057

 0.9548346831045906


24. What are the differences between Pandas Series and NumPy arrays?

YOUR ANSWER HERE 
-When we have to work on Tabular data, we prefer the pandas module. When we have to work on Numerical data, we prefer the numpy module.
-The powerful tools of pandas are Data frame and Series. Whereas the powerful tool of numpy is Arrays.
-Pandas consume more memory. Numpy is memory efficient.
-Pandas has a better performance when a number of rows is 500K or more. Numpy has a better performance when number of rows is 50K or less.
-Indexing of the pandas series is very slow as compared to numpy arrays. Indexing of numpy Arrays is very fast.
-Pandas offer a have2d table object called DataFrame. Numpy is capable of providing multi-dimensional arrays.
-It was developed by Wes McKinney and was released in 2008. It was developed by Travis Oliphant and was released in 2005.
-It has a higher industry application. It has a lower industry application.
(You can find the information on the geeksforgeeks website)

25. Create a 5-element series with different data types, with an index of capital letters.

In [110]:
# YOUR CODE HERE
a = [1, 'Hello', 3.5, True, 9]
s = pd.Series(a, index = ["A", "B", "C", "D", "E"])
print(s)

A        1
B    Hello
C      3.5
D     True
E        9
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [113]:
# YOUR CODE HERE
a = {'Turkey':'Ankara', 'UK':'London', 'Belgium':'Brussels','Netherlands':'Amsterdam','Egypt':'Cairo'}
s = pd.Series(a)
print(s)

Turkey            Ankara
UK                London
Belgium         Brussels
Netherlands    Amsterdam
Egypt              Cairo
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [146]:
# YOUR CODE HERE
array = np.random.randint(20, size=10)
a = pd.Series(array, index= ['a', 'b', 'c', 'd', 'e', 'f', 'k', 'l', 'm', 'n'])
print(a)
print('\n', a['m'])
print('\n', a[0])
print('\n', a['b'],a['k'])


a    13
b     4
c    10
d     7
e    17
f     6
k    17
l    13
m    16
n     3
dtype: int64

 16

 13

 4 17


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [145]:
# YOUR CODE HERE
ser1= ['appel', 'aardbei', 'wortel', 'sinaasappel', 'aardappel']
ser2 = ['a', 'b', 'c', 'd', 'e']
ser1 = pd.Series(ser1)
ser2 = pd.Series(ser2)
both1 = pd.concat([ser1, ser2])
both2 = pd.concat([ser1, ser2], ignore_index= True)
print(both1)

print('\n', both2)

0          appel
1        aardbei
2         wortel
3    sinaasappel
4      aardappel
0              a
1              b
2              c
3              d
4              e
dtype: object

 0          appel
1        aardbei
2         wortel
3    sinaasappel
4      aardappel
5              a
6              b
7              c
8              d
9              e
dtype: object


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [168]:
# YOUR CODE HERE
import time
starting_point = time.time()
while True:
    difference = np.random.rand(5, 5) - np.random.rand(5, 5)
    # print(difference)
    diagonal = np.diag(difference)
    if (diagonal < 0.1).all() and (diagonal > -0.1).all():
        end_point = time.time()
        print("Time it took: ", end_point - starting_point)
        print("The matrix is:", diagonal)
        break


Time it took:  0.012932300567626953
The matrix is: [ 0.05688423 -0.06957167  0.061774   -0.02813587  0.04745108]
