## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [40]:
# imports, no need to edit

import numpy as np
import pandas as pd
from numpy import random

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

the vector is one dimensional array, while the matrix is 2 dimensional which has rows and colomns! 

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [31]:
# YOUR CODE HERE
np.zeros((10,10)).astype(int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.zeros((10,10), dtype=(int))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [33]:
# YOUR CODE HERE
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [34]:
# YOUR CODE HERE
np.ones((10,10)).astype(int)*9

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [38]:
# YOUR CODE HERE
np.arange(5, 25, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [39]:
# YOUR CODE HERE
np.linspace(-1, 1, num=30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [42]:
# YOUR CODE HERE
x = random.randint(30, size=(5, 6))
x

array([[ 0, 11, 25, 21, 28, 11],
       [24, 16, 26, 26,  9, 27],
       [27, 15, 14, 29, 29, 14],
       [29, 18, 11, 22, 19, 24],
       [ 2,  4, 18,  6, 20,  8]])

9. Create an array of 30 random integers and sort it in ascending order.

In [61]:
# YOUR CODE HERE
arr = random.randint(600, size=30).astype(int)
print(np.sort(arr))

[ 11  34  42  74  89  98 114 167 191 195 252 267 276 284 301 375 393 396
 412 416 417 419 426 456 492 498 500 547 555 576]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [65]:
# YOUR CODE HERE
e = np.ones((5,10))
print(e.size)
print(e.shape)
print(e.dtype)


50
(5, 10)
float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [66]:
# YOUR CODE HERE
np.random.randint(0, 10, size=(3,4,7))

array([[[1, 0, 6, 7, 6, 4, 0],
        [6, 6, 8, 2, 8, 0, 0],
        [3, 8, 5, 2, 0, 3, 8],
        [2, 8, 6, 3, 2, 9, 4]],

       [[4, 2, 8, 3, 4, 3, 4],
        [6, 8, 6, 4, 9, 9, 6],
        [9, 4, 2, 6, 1, 8, 9],
        [9, 0, 5, 6, 7, 9, 8]],

       [[1, 9, 1, 4, 4, 5, 2],
        [7, 0, 5, 3, 0, 6, 8],
        [3, 3, 5, 2, 5, 6, 9],
        [9, 2, 6, 2, 1, 9, 3]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [78]:
# YOUR CODE HERE
c = np.random.randint(70, size=20, dtype=int)
print(c)
print(c.reshape((4, 5)))

[13 65 50 37 63 37 49 29 50 62 51 37 29 50  4 28  3  9 55 16]
[[13 65 50 37 63]
 [37 49 29 50 62]
 [51 37 29 50  4]
 [28  3  9 55 16]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [83]:
# YOUR CODE HERE
a = np.array([1, 2, 10])
b = np.array([3, 3, 44])
c = np.array([9, 12, 0])
np.concatenate((a, b, c))

array([ 1,  2, 10,  3,  3, 44,  9, 12,  0])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [92]:
# YOUR CODE HERE
e = np.arange(3)
print(e)
d = np.random.randint(40, size=(3,3))
print(d)
e + d

[0 1 2]
[[28 31 18]
 [20  4 17]
 [27 21 20]]


array([[28, 32, 20],
       [20,  5, 19],
       [27, 22, 22]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis=1 is the second axis, when talking about multi-dimensional arrays, axis 1 is the axis that runs forward the colomns.
axis=0 is the first axis, when talking about multi-dimensional arrays, axis 0 is the axis that runs downward down the rows.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [99]:
# YOUR CODE HERE
r = np.random.randint(20, 100, 20)
print(r)
print(r[2])
print(r[4])
print(r[6])

[81 79 69 97 94 28 53 95 54 20 59 83 41 79 83 91 30 33 79 49]
69
94
53


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [105]:
# YOUR CODE HERE
g = np.random.randint(100,size=10)
print(g)
g[3]=100
print(g)

[71 41 63 14 28 32 93 26 35 28]
[ 71  41  63 100  28  32  93  26  35  28]


18. Look up the concepts of * diagonal matrix* and *trace matrix*online and write a small explanation about what they are.


Diagonal matrix is a matrix (usually a square matrix of order n) filled with values on the main diagonal and zeros everywhere else.
Trace of Matrix is the sum of main diagonal elements of the matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [113]:
# YOUR CODE HERE
v = [3, 2, 5, 6, 9]
e = np.diag(v)
print(e)
np.diag_indices(5, ndim=5)

[[3 0 0 0 0]
 [0 2 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 9]]


(array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]))

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [122]:
# YOUR CODE HERE
x = np.arange(10, 20)
x[3 : ]


array([13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [148]:
# YOUR CODE HERE
np.random.seed(42)
w = random.randint(90, size=(10,10)).astype(int)
print("0=",w)
print("1=",w[2, 4])
print("2=",w[:, 4])
print("3=",w[1, :])
print("4=",w[1, :7])
print("5=",w[2:5, 3:7])
print("6=",w[5:, :4])


0= [[51 14 71 60 20 82 86 74 74 87]
 [23  2 21 52  1 87 29 37  1 63]
 [59 20 32 75 57 21 88 48 58 41]
 [59 79 14 61 61 46 61 50 54 63]
 [ 2 50  6 20 72 38 17  3 88 59]
 [13  8 89 52  1 83 59 70 43  7]
 [46 34 77 80 35 49  3  1  5 53]
 [ 3 53 62 17 89 43 33 73 61 13]
 [47 14 71 77 86 61 39 84 79 81]
 [52 23 25 88 59 40 28 14 44 64]]
1= 57
2= [20  1 57 61 72  1 35 89 86 59]
3= [23  2 21 52  1 87 29 37  1 63]
4= [23  2 21 52  1 87 29]
5= [[75 57 21 88]
 [61 61 46 61]
 [20 72 38 17]]
6= [[13  8 89 52]
 [46 34 77 80]
 [ 3 53 62 17]
 [47 14 71 77]
 [52 23 25 88]]


In [150]:
print(w[4, 4])
w[4, 4] = 1992
print("7=",w)

92
7= [[  51   14   71   60   20   82   86   74   74   87]
 [  23    2   21   52    1   87   29   37    1   63]
 [  59   20   32   75   57   21   88   48   58   41]
 [  59   79   14   61   61   46   61   50   54   63]
 [   2   50    6   20 1992   38   17    3   88   59]
 [  13    8   89   52    1   83   59   70   43    7]
 [  46   34   77   80   35   49    3    1    5   53]
 [   3   53   62   17   89   43   33   73   61   13]
 [  47   14   71   77   86   61   39   84   79   81]
 [  52   23   25   88   59   40   28   14   44   64]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [165]:
# YOUR CODE HERE
arr = np.arange(0, 50, 5)
print(arr)
a = arr>20
print(arr[a])
b = arr < 30
print(arr[b])
c = arr.size
print(c)
print(arr * 5)



[ 0  5 10 15 20 25 30 35 40 45]
[25 30 35 40 45]
[ 0  5 10 15 20 25]
10
[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [178]:
# YOUR CODE HERE
arr = np.linspace(0, 1, num=50)
print(arr)
print("a:", arr.mean())
print("b:", arr.std())
print("c:", arr.var())
import statistics
print("d:", statistics.median(arr))
print("e:", arr.min())
print("f:", arr.max())

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
a: 0.5
b: 0.2945075446869757
c: 0.086734693877551
d: 0.5
e: 0.0
f: 1.0


24. What are the differences between Pandas Series and NumPy arrays?

the presence of the index, while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values. 

25. Create a 5-element series with different data types, with an index of capital letters.

In [182]:
# YOUR CODE HERE
a = [1, 7.5, "n", "L", 13]
s = pd.Series(a , index = ["A", "B", "C", "D", "E"])
s

A      1
B    7.5
C      n
D      L
E     13
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [183]:
# YOUR CODE HERE
d = {"Syria": "Damascus", "France": "Paris", "Egypt": "Cairo", "USA": "Washington", "Netherland": "Amsterdam"}
pd.Series(d)

Syria           Damascus
France             Paris
Egypt              Cairo
USA           Washington
Netherland     Amsterdam
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [25]:
# YOUR CODE HERE


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [26]:
# YOUR CODE HERE

**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [27]:
# YOUR CODE HERE