## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [2]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vecotor is one dimensional array while a matrix is 2d


2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE

lis= list (range(11))
lis= np.array(lis)
lis

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [4]:
# YOUR CODE HERE
z=np.zeros((10,10), dtype=np.int64)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

4. Construct a 10x10 matrix filled with '1's, data type float.

In [6]:
# YOUR CODE HERE
o=np.ones((10,10), dtype=np.float64)
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [8]:
# YOUR CODE HERE
n= z +9
n

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int64)

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [10]:

# YOUR CODE HERE
r=np.arange (5,25,3)
r

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [11]:
# YOUR CODE HERE
a30=np.linspace(-1, 1, num=30)
a30

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [14]:
# YOUR CODE HERE
i= np.arange(30)
i.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [22]:
# YOUR CODE HERE
np.random.seed(42)
rand= np.random.randint(20 , size=30)
rand.sort()
rand

array([ 0,  1,  1,  2,  2,  3,  4,  5,  6,  6,  7,  7,  9, 10, 10, 10, 11,
       11, 11, 11, 14, 14, 14, 15, 16, 18, 18, 18, 19, 19])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [28]:
# YOUR CODE HERE
o= np.ones((5*10))
print (f"number of elements: {o.size}")
print (f"shape of the matrix {o.shape}")
print (f"the data type: {o.dtype}")


number of elements: 50
shape of the matrix (50,)
the data type: float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [32]:
# YOUR CODE HERE
np.random.seed(42)
d= np.random.randint(10, size=(3,4,7))
d

array([[[6, 3, 7, 4, 6, 9, 2],
        [6, 7, 4, 3, 7, 7, 2],
        [5, 4, 1, 7, 5, 1, 4],
        [0, 9, 5, 8, 0, 9, 2]],

       [[6, 3, 8, 2, 4, 2, 6],
        [4, 8, 6, 1, 3, 8, 1],
        [9, 8, 9, 4, 1, 3, 6],
        [7, 2, 0, 3, 1, 7, 3]],

       [[1, 5, 5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7, 6, 8],
        [7, 4, 1, 4, 7, 9, 8],
        [8, 0, 8, 6, 8, 7, 0]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [35]:
# YOUR CODE HERE

aa= np.random.randint ( 100,size=20)
aa.reshape ( 4,5)


array([[61, 87, 36, 98, 43],
       [85, 90, 34, 64, 98],
       [46, 77,  2,  0,  4],
       [89, 13, 26,  8, 78]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [41]:
# YOUR CODE HERE
first=np.arange(5)
second=np.arange(5,10)
third =np.arange(10,15)
fourth=np.arange(15,20)
all=np.concatenate ( (first , second,third,fourth) ) 
all

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [47]:
# YOUR CODE HERE

v=np.array([1,1,1])
m=np.zeros((3,3))
np.vstack((v,m))
#did not understand what a 'column-by-column basis' means though

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis=0 the operation will be applied on every column ( vertical movement) 
axis=1 :the operation will be applied on every row ( horizantal  movement) 

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [53]:
# YOUR CODE HERE
b= np.arange ( 1,21)
print( b[2])
print(b[4])
print(b[6])

3
5
7


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [57]:
# YOUR CODE HERE
 
dt= np.arange(10)
print ( dt)
dt[3]=99
print ( dt)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 99  4  5  6  7  8  9]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


- Diagonal matrix is a 2d matrix, where all its element other than the main diagnosal are zeros. Its shape can be square or rectagle, in the last case, all elements other than items(i,i) are zeros.
- the trace of a matrix is the sum of all elements in its main diagnosal, it is defined only for a square matrix

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [67]:
# YOUR CODE HERE
diagnosal = np.zeros ( (5,5))
l=[1,2,3,4,5]
np.fill_diagonal ( diagnosal, l )
print (diagnosal)
print (f" indices are : {np.diag_indices(5)}")


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
 indices are : (array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [69]:
# YOUR CODE HERE
w= np.arange ( 10,20)
w[2:]

array([12, 13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [73]:

# YOUR CODE HERE
np.random.seed(42)
ra= np.random.randint(10, size=(10,10))
print ( ra)

print ( f"column 5 of row 3 : {ra[3,5]}" )
print ( f"all elements of column 5: {ra[:,5]}" )
print ( f"the 2nd row of all columns: {ra[2,:]}" )
print ( f" row 2 through 7 of all columns. : {ra[2:8,:]}" )
print ( f"values with row index 2 to 5 and column index 3 to 7. : {ra[2:6,3:8]}" )
print ( f"values from row index 5 to the end and column index from the top to 4. : {ra[5:,:5]}" )
ra[4,4]=1993
print ( ra)

[[6 3 7 4 6 9 2 6 7 4]
 [3 7 7 2 5 4 1 7 5 1]
 [4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3]
 [8 1 9 8 9 4 1 3 6 7]
 [2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8]
 [7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7]]
column 5 of row 3 : 4
all elements of column 5: [9 4 0 4 4 3 9 9 7 9]
the 2nd row of all columns: [4 0 9 5 8 0 9 2 6 3]
 row 2 through 7 of all columns. : [[4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3]
 [8 1 9 8 9 4 1 3 6 7]
 [2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8]
 [7 4 1 4 7 9 8 8 0 8]]
values with row index 2 to 5 and column index 3 to 7. : [[5 8 0 9 2]
 [2 6 4 8 6]
 [8 9 4 1 3]
 [1 7 3 1 5]]
values from row index 5 to the end and column index from the top to 4. : [[2 0 3 1 7]
 [3 5 1 9 1]
 [7 4 1 4 7]
 [6 8 7 0 7]
 [2 0 4 9 6]]
[[   6    3    7    4    6    9    2    6    7    4]
 [   3    7    7    2    5    4    1    7    5    1]
 [   4    0    9    5    8    0    9    2    6    3]
 [   8    2    4    2    6    4    8    6    1    3]
 [   8    1    

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [77]:
# YOUR CODE HERE
y= np.arange ( 0,50, 5)
print ( y)
print ( f" all values greater than 20 { y[y>20]}")
print ( f"  all values less than 30. { y[y<30]}")

# did not understand what does 'values are 33 in it' mean ?
print ( f" How many values are 33 in it? { len( y[y==33])}")
y*=5
y

[ 0  5 10 15 20 25 30 35 40 45]
 all values greater than 20 [25 30 35 40 45]
  all values less than 30. [ 0  5 10 15 20 25]
 How many values are 33 in it? 0


array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [88]:
# YOUR CODE HERE
f= np.random.rand(1,50 )
print (f"the standard deviation.{np.std(f)}")
print (f"the variance: {np.var(f)}")
print (f"the median : {np.median (f)}")
print (f" smallest value {f.min()}")
print (f" largest value {f.max()}")

the standard deviation.0.2673340006927679
the variance: 0.07146746792640082
the median : 0.4974965783282541
 smallest value 0.04340078329817276
 largest value 0.9779006687542708


24. What are the differences between Pandas Series and NumPy arrays?

NumPy arrays can only store elements of the same data type, whereas Pandas Series can store elements of different data types.

25. Create a 5-element series with different data types, with an index of capital letters.

In [89]:
# YOUR CODE HERE
dic= { 'A' : 1,
     'B' : "000",
     'C': 1.2,
     'D' : [1,2,3],
     'E': {'1': 1}}
pd.Series(dic)

A            1
B          000
C          1.2
D    [1, 2, 3]
E     {'1': 1}
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [91]:
# YOUR CODE HERE
c= { 'France' :'Paris',
     'UK' : "London",
     'USA': 'WDC',
     'UAE' : 'AbuDhabi',
     'NL': 'AMS'}
pd.Series(c)

France       Paris
UK          London
USA            WDC
UAE       AbuDhabi
NL             AMS
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [106]:
# YOUR CODE HERE
vec= np.random.randint (10, size=10)
letters='abcdefghij'
indeces=[]
for i in letters : 
    indeces.append(i)
 
s=pd.Series (vec, index= indeces)
print (s)
print (f"  the 3rd element of the series using the index name  {s['c']}")
print (f"  1st element of the series using the index number  {s[0]}")
print (f"  2nd : {s['b']} and 7th : {s['g']}")


a    7
b    3
c    7
d    8
e    2
f    2
g    1
h    9
i    2
j    2
dtype: int32
  the 3rd element of the series using the index name  7
  1st element of the series using the index number  7
  2nd : 3 and 7th : 1


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [118]:
# YOUR CODE HERE
a1 = list ( range ( 30,36))
a2=  list ( range ( 36,40))
a1=pd.Series(a1)
a2=pd.Series(a2)
a3=pd.concat([a1,a2])
 

print (f" Combine the series you have created \n {a3}")
a3.index=list ( range ( 1,11))
print (f" Combine the series you have created  \n {a3}")


 Combine the series you have created 
 0    30
1    31
2    32
3    33
4    34
5    35
0    36
1    37
2    38
3    39
dtype: int64
 Combine the series you have created  
 1     30
2     31
3     32
4     33
5     34
6     35
7     36
8     37
9     38
10    39
dtype: int64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [ ]:
# YOUR CODE HERE