## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [2]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.
A vector is a one-dimensional array and a matrix is more then one-dimensional array in NumPy.

YOUR ANSWER HERE

2. Construct a NumPy Array from a list of 10 elements.

In [7]:
list_a=list(range(10))
print(list_a)
arr=np.array(list_a)
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [11]:
# YOUR CODE HERE
matrix=np.full((5,5),0, dtype=int)
matrix2=np.zeros((5,5),dtype=int)
print(matrix)
matrix2


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [12]:
matrix=np.full((10,10),1, dtype=float)
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [ ]:
matrix=np.full((10,10),9, dtype=int)
matrix

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [15]:
arr=np.arange(5,25,3)
arr

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [21]:
arr = np.linspace(-1, 1, 30)
print(arr)

arr = np.random.uniform(-1, 1, 30)
print(arr)

arr = np.random.rand(30)*2-1
print(arr)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]
[-0.10109865 -0.80917977 -0.2583635   0.33768251  0.33184471  0.18259558
 -0.45055641  0.12248685 -0.23414625  0.94342419  0.69782765  0.44345904
 -0.52803016 -0.48786335 -0.91913282  0.42132578 -0.77821836 -0.121327
 -0.5965616   0.79152719 -0.04925955  0.12655114  0.39103217 -0.72133709
  0.20883476  0.07968218 -0.59387755  0.88570714  0.19773093  0.38956987]
[ 0.76093568  0.2487081  -0.40873263 -0.78901148 -0.08693086 -0.56311913
 -0.1669801   0.76656052 -0.35130996 -0.75582409 -0.28740432  0.81365688
 -0.4557355   0.29538024 -0.99895925 -0.29486229 -0.39043748 -0.67068829
  0.06817884 -0.03034006  0.38487207 -0.46117533 -0.

8. Construct a 5x6 matrix with integers from 0 to 30.

In [22]:
arr=np.random.randint(0,30,size=(5,6))
arr

array([[ 6,  1,  2, 16,  4, 16],
       [23, 16, 26, 16,  1,  1],
       [27, 21, 22,  4,  0,  0],
       [18, 29,  1, 20, 11, 25],
       [ 5, 22,  3, 22, 10, 23]])

9. Create an array of 30 random integers and sort it in ascending order.

In [25]:
arr=np.random.randint(30,size=(30))[::-1]
arr=np.sort(arr)
arr

array([ 0,  0,  0,  1,  2,  6,  6,  7,  7,  8,  9, 10, 15, 15, 15, 16, 17,
       17, 19, 19, 22, 24, 24, 24, 25, 27, 27, 27, 29, 29])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [28]:
matrix=np.ones((5,10),dtype=int)
print(matrix)
print(matrix.size)
print(matrix.shape)
print(matrix.dtype)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
50
(5, 10)
int32


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [29]:
matrix=np.random.randint(10,size=(3,4,7))
matrix

array([[[5, 7, 1, 4, 0, 0, 4],
        [2, 3, 2, 0, 0, 4, 5],
        [2, 8, 4, 7, 0, 4, 2],
        [0, 3, 4, 6, 0, 2, 1]],

       [[8, 9, 5, 9, 2, 7, 7],
        [1, 5, 6, 1, 9, 1, 9],
        [0, 7, 0, 8, 5, 6, 9],
        [6, 9, 2, 1, 8, 7, 9]],

       [[6, 8, 3, 3, 0, 7, 2],
        [6, 1, 1, 6, 5, 2, 8],
        [9, 5, 9, 9, 5, 0, 3],
        [9, 5, 5, 4, 0, 7, 4]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [30]:
matrix=np.random.randint(20,size=(20))
matrix=matrix.reshape(4,5)
matrix

array([[11, 11,  4,  6,  3],
       [ 5, 12, 19, 14,  2],
       [ 7, 19, 15, 12, 17],
       [ 9, 18, 16, 18,  4]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [31]:
arr1=np.random.randint(10,size=(4))
arr2=np.random.randint(10,size=(4))
arr3=np.random.randint(10,size=(4))
arr4=np.random.randint(10,size=(4))
arr=np.concatenate((arr1,arr2,arr3,arr4))
arr

array([9, 4, 6, 8, 4, 0, 9, 9, 0, 1, 5, 8, 7, 4, 0, 6])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [34]:
vector=np.random.randint(10,size=(3)).reshape(3,1)
print(vector)
matrix=np.random.randint(10,size=(3,3))
print(matrix)
result=np.column_stack((matrix,vector))
result

[[4]
 [3]
 [1]]
[[3 9 9]
 [2 9 0]
 [7 4 3]]


array([[3, 9, 9, 4],
       [2, 9, 0, 3],
       [7, 4, 3, 1]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 
"axis=0" refers to the direction along the rows and "axis=1" refers to the direction along the columns.

YOUR ANSWER HERE

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [35]:
arr=np.random.randint(10,size=(20))
print(arr[2])
print(arr[4])
print(arr[6])

1
3
1


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [37]:
arr=np.random.randint(10,size=(10))
print(arr)
arr[3]=11
arr

[8 3 9 4 8 7 2 0 2 3]


array([ 8,  3,  9, 11,  8,  7,  2,  0,  2,  3])

18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.
A diagonal matrix is a square matrix in which all the entries outside the main diagonal are zero. The main diagonal of a matrix is the diagonal from the top left corner to the bottom right corner.
 [[1, 0, 0],
 [0, 2, 0],
 [0, 0, 3]]

 the sum of 1+2+3 is trace matrix


YOUR ANSWER HERE

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [43]:
matrix = np.diag([1, 2, 3, 4, 5])
matrix[0,0]
matrix[1,1]
matrix[2,2]
matrix[3,3]
matrix[4,4]
matrix = np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [44]:
arr=np.arange(10,20)
print(arr[2:])

[12 13 14 15 16 17 18 19]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [61]:
np.random.seed(42)
matrix=np.random.randint(20,size=(10,10))
print(matrix)
#Retrieve column 5 of row 3. Moreover;
print(matrix[2,4])
#Retrieve all elements of column 5.
print(matrix[:,4])
#Retrieve the 2nd row of all columns.
print(matrix[1,:])
#Retrieve row 2 through 7 of all columns.
print(matrix[1,6:])
#Retrieve values with row index 2 to 5 and column index 3 to 7.
print(matrix[1:6,2:8])
#Retrieve the values from row index 5 to the end and column index from the top to 4.
print(matrix[4:, :4])
#Replace the value corresponding to the 5th row and the 5th column with your year of birth.
matrix[4,4]=1985
matrix


[[ 6 19 14 10  7  6 18 10 10  3]
 [ 7  2  1 11  5  1  0 11 11 16]
 [ 9 15 14 14 18 11 19  2  4 18]
 [ 6  8  6 17  3 13 17  8  1 19]
 [14  6 11  7 14  2 13 16  3 17]
 [ 7  3  1  5  9  3 17 11  1  9]
 [ 3 13 15 14  7 13  7 15 12 17]
 [14 12  8 14 12  0  6  8  0 11]
 [ 7 10 18 16  7  2  2  0  4  9]
 [ 6  8  6  8  7 11  1  0 15  4]]
18
[ 7  5 18  3 14  9  7 12  7  7]
[ 7  2  1 11  5  1  0 11 11 16]
[ 0 11 11 16]
[[ 1 11  5  1  0 11]
 [14 14 18 11 19  2]
 [ 6 17  3 13 17  8]
 [11  7 14  2 13 16]
 [ 1  5  9  3 17 11]]
[[14  6 11  7]
 [ 7  3  1  5]
 [ 3 13 15 14]
 [14 12  8 14]
 [ 7 10 18 16]
 [ 6  8  6  8]]


array([[   6,   19,   14,   10,    7,    6,   18,   10,   10,    3],
       [   7,    2,    1,   11,    5,    1,    0,   11,   11,   16],
       [   9,   15,   14,   14,   18,   11,   19,    2,    4,   18],
       [   6,    8,    6,   17,    3,   13,   17,    8,    1,   19],
       [  14,    6,   11,    7, 1985,    2,   13,   16,    3,   17],
       [   7,    3,    1,    5,    9,    3,   17,   11,    1,    9],
       [   3,   13,   15,   14,    7,   13,    7,   15,   12,   17],
       [  14,   12,    8,   14,   12,    0,    6,    8,    0,   11],
       [   7,   10,   18,   16,    7,    2,    2,    0,    4,    9],
       [   6,    8,    6,    8,    7,   11,    1,    0,   15,    4]])

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [66]:
arr=np.arange(0,50,5)
print(arr[arr>20])
print(arr[arr<30])
print(np.count_nonzero(arr == 33))
print(arr*5)

[25 30 35 40 45]
[ 0  5 10 15 20 25]
0
[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [70]:
arr=np.random.random(50)
print(arr.std())
print(arr.var())
print(arr.mean())
print(arr.min())
print(arr.max())

0.2780291454529019
0.07730020572127089
0.5197250532431947
0.005061583846218687
0.9730105547524456


24. What are the differences between Pandas Series and NumPy arrays?
Pandas Series and NumPy arrays are both used for storing and manipulating data in Python, but there are some key differences between the two:

Indexing: Pandas Series have an explicit index, which means that each element in the Series has a label. NumPy arrays, on the other hand, do not have an explicit index and elements are accessed using their integer position.

Data Types: NumPy arrays can only hold elements of a single data type, whereas Pandas Series can hold elements of different data types.

Handling missing data: Pandas Series have built-in support for handling missing data (i.e., NaN values), whereas NumPy arrays do not.

Additional functionalities: Pandas Series have additional functionalities such as handling time-series data, handling missing data, and data alignment, which NumPy arrays don't have.

Memory consumption: Pandas Series are less memory efficient than NumPy arrays because of the additional functionalities and metadata they have.

In summary, Pandas Series are built on top of NumPy arrays and provide additional functionalities and flexibility, while NumPy arrays are more efficient and simpler to use.

YOUR ANSWER HERE

25. Create a 5-element series with different data types, with an index of capital letters.

In [71]:
data = {'A': 1, 'B': 'Hello', 'C': 3.14, 'D': [1, 2, 3], 'E': (1, 2)}
s = pd.Series(data)
print(s)

data = [1, 'Hello', 3.14, [1, 2, 3], (1, 2)]
index = ['A', 'B', 'C', 'D', 'E']
s = pd.Series(data, index=index)
print(s)


A            1
B        Hello
C         3.14
D    [1, 2, 3]
E       (1, 2)
dtype: object
A            1
B        Hello
C         3.14
D    [1, 2, 3]
E       (1, 2)
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [73]:
data = {
    "Netherlands": "Amsterdam",
    "Germany": "Berlin",
    "Spain": "Madrid",
    "Italy": "Rome",
    "Greece": "Athens",
}
s = pd.Series(data)
print(s)

s = pd.Series(data,name='Capital Cities')
print(s)

Netherlands    Amsterdam
Germany           Berlin
Spain             Madrid
Italy               Rome
Greece            Athens
dtype: object
Netherlands    Amsterdam
Germany           Berlin
Spain             Madrid
Italy               Rome
Greece            Athens
Name: Capital Cities, dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [79]:
vec=np.random.rand(10)
index=["a","b","c","d","e",'f','g',"h",'i','j']
serie=pd.Series(vec,index=index)
print(serie["c"])
print(serie[0])
print(serie[["b",'g']])

0.2865412521282844
0.46559801813246016
b    0.542645
g    0.822601
dtype: float64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [84]:
vec=np.random.randint(10,size=(5))
vec2=np.random.randint(10,20,size=(5))
s1=pd.Series(vec)
s2=pd.Series(vec2)
s=pd.concat([s1,s2])
print(s)
s.index = range(1, len(s) + 1)
print(s)


0     9
1     2
2     4
3     5
4     8
0    14
1    10
2    13
3    14
4    19
dtype: int32
1      9
2      2
3      4
4      5
5      8
6     14
7     10
8     13
9     14
10    19
dtype: int32


**Bonus homework**:
Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


count=0
while True:
    count+=1    
    matrix=np.random.rand(20,20)
    matrix2=np.random.rand(20,20)
    difference=matrix-matrix2
    difference=np.diag(difference)
    a=np.count_nonzero(difference[ (difference>-0.1) & (difference<0.1)]) 
    #a = len(np.where((difference > -0.1) & (difference < 0.1))[0])
    #a = np.sum((difference > -0.1) & (difference < 0.1))    
    if a == difference.size:      
        print(difference) 
        print(count)       
        break


        
