## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [4]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

YOUR ANSWER HERE

2. Construct a NumPy Array from a list of 10 elements.

In [6]:
x= np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [49]:
x= np.zeros((10,10), dtype='int32')
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [150]:
x= np.ones((10,10),dtype= 'float32')
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [12]:
x= np.full((10,10), 9)
x

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [15]:
x=np.arange(5,25,3)
x


array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [17]:
x=np.linspace(-1,1,30)
x


array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [20]:
x= np.random.randint(30, size=(5,6))
x

array([[ 6, 17,  3, 24, 27, 13],
       [17, 25,  8, 25, 20,  1],
       [19, 27, 14, 27,  6, 11],
       [28,  7, 14,  2, 13, 16],
       [ 3, 17,  7,  3,  1, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [160]:
x= np.random.randint(1000, size=(30))
np.sort(x)


array([ 27,  35,  85,  95, 159, 170, 230, 240, 242, 406, 484, 524, 540,
       555, 556, 563, 573, 577, 619, 645, 654, 681, 698, 733, 748, 795,
       795, 838, 899, 952])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [162]:
x= np.ones((5,10), dtype=np.int32)
print(x)
print(x.size)
print(x.shape)
print(x.dtype)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
50
(5, 10)
int32


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [43]:
x= np.random.randint(0,11, size=(3,4,7))
x

array([[[5, 7, 8, 3, 0, 0, 9],
        [3, 6, 1, 2, 0, 4, 0],
        [7, 0, 0, 1, 1, 5, 6],
        [4, 0, 0, 2, 1, 4, 9]],

       [[5, 6, 3, 6, 7, 0, 5],
        [7, 4, 3, 1, 5, 5, 0],
        [8, 5, 2, 3, 3, 2, 9],
        [2, 2, 3, 6, 3, 8, 0]],

       [[7, 6, 1, 7, 0, 8, 8],
        [1, 6, 9, 2, 6, 9, 8],
        [3, 0, 1, 0, 4, 4, 6],
        [8, 8, 2, 2, 2, 3, 7]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [45]:
x= np.random.randint(100, size=(20))
x.reshape(4,5)

array([[40, 99, 32, 67, 32],
       [13, 20, 47, 19,  7],
       [ 6, 66, 16, 32, 47],
       [75, 58, 85, 21, 29]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [47]:
x1= np.array([2,3])
x2= np.array([4,5])
x3= np.array([6,7])
x4= np.array([8,9])
np.concatenate((x1,x2,x3,x4))

array([2, 3, 4, 5, 6, 7, 8, 9])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [50]:
x1= np.array([1,2,3])
x2= np.array([[6,5,9],[4,6,8],[9,4,7]])
np.vstack([x1, x2])

array([[1, 2, 3],
       [6, 5, 9],
       [4, 6, 8],
       [9, 4, 7]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis= 0 is reffering to the data in across columns
axis= 1 is reffering to the data in across rows

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [63]:
np.random.seed(42)
x= np.random.randint(100, size=20)
print(x)
print(x[2])
print(x[4])
print(x[6])

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
14
60
82


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [64]:
np.random.seed(42)
x= np.random.randint(100, size=10)
x[3]= 112
x

array([ 51,  92,  14, 112,  60,  20,  82,  86,  74,  74])

18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


diagonal matrix is a square matrix in which every element except the principal diagonal elements is zero.
trace of matrixis  the sum of elements of the principal diagonal of a square matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [170]:

x= np.array([[6,5,9,4,2],[4,6,8,9,1],[9,4,7,2,1],[3,6,4,9,0],[2,0,0,9,1]])
print(x)
print(x[0,0], x[1,1], x[2,2], x[3,3],x[4,4])

[[6 5 9 4 2]
 [4 6 8 9 1]
 [9 4 7 2 1]
 [3 6 4 9 0]
 [2 0 0 9 1]]
6 6 7 9 1


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [71]:
x= np.arange(10,21)
x[3:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [86]:
np.random.seed(42)
x = np.random.randint(100, size=(10,10))
print(x)
print(x[2,4])
print(x[:,4])
print(x[1,:])
print(x[1,:7])
print(x[2:5,3:7])
print(x[5:,:4])
x[4,4]= 1997
print(x)

[[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]
32
[60 21 32 59  2 13  7 53 61 39]
[87 99 23  2 21 52  1 87 29 37]
[87 99 23  2 21 52  1]
[[20 32 75 57]
 [91 59 79 14]
 [63  2 50  6]]
[[17  3 88 59]
 [91 59 70 43]
 [49  3  1  5]
 [89 43 33 73]
 [71 77 86 61]]
[[  51   92   14   71   60   20   82   86   74   74]
 [  87   99   23    2   21   52    1   87   29   37]
 [   1   63   59   20   32   75   57   21   88   48]
 [  90   58   41   91   59   79   14   61   61   46]
 [  61   50   54   63 1997   50    6   20   72   38]
 [  17    3   88   59   13    8   89   52    1   83]
 [  91   59   70   43    7   46   34   77   80   35]
 [  49    3    1    5   53    3   53   92   62   17]
 [  89   43   33   73   61   99  










22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [163]:
x= np.arange(0,51,5)
print(x[x>20])
print(x[x<30])
print(np.sum(x==33))
print(x*5)

[25 30 35 40 45 50]
[ 0  5 10 15 20 25]
0
[  0  25  50  75 100 125 150 175 200 225 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [110]:
x= np.random.rand(50)
print(x.mean())
print(x.std())
print(np.median(x))
print(x.min())
print(x.max())


0.5530970721842713
0.29507601826737473
0.5691848867124183
0.015456616528867428
0.015456616528867428
0.9900538501042633


24. What are the differences between Pandas Series and NumPy arrays?

in panda you can set indexing method in array, you can also name your rows and columns and you can retrive date by the name of the array, unlike in numpy , arrays could be just indexed by the default indexing method!

25. Create a 5-element series with different data types, with an index of capital letters.

In [112]:
x = [1.5, 7, 'Fenyx',[1,3,4],{5,6.7,8}]
pd.Series(x, index = ["A", "B", "C","D","E"])

A            1.5
B              7
C          Fenyx
D      [1, 3, 4]
E    {8, 5, 6.7}
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [164]:
x = {"Netherlands": "Amsterdam", "Hungary": "Budapest", "Yemen": "Sanaa", "Germany": "Berlin", "Egypt": "Cairo"}
pd.Series(x)

Netherlands    Amsterdam
Hungary         Budapest
Yemen              Sanaa
Germany           Berlin
Egypt              Cairo
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [124]:
np.random.seed(42)
x = np.random.randint(100, size=10)
print(x)
s= pd.Series(x, index = ["A", "B", "C","D","E","F","G","H","I","J"])
print(s['C'])
print(s[0])
print(s['B'] , s['G'])

[51 92 14 71 60 20 82 86 74 74]
14
51
92 82


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [149]:
s1= pd.Series(["a", "b", "c", "d","e"])
s2= pd.Series(["f", "g", "h", "i","j"])
print(s1.append(s2))
z= pd.concat([s1, s2], axis = 0)
z.index= np.arange(1,(len(s1) + len(s2))+1)
print(z)

0    a
1    b
2    c
3    d
4    e
0    f
1    g
2    h
3    i
4    j
dtype: object
1     a
2     b
3     c
4     d
5     e
6     f
7     g
8     h
9     i
10    j
dtype: object


C:\Users\ghass\AppData\Local\Temp\ipykernel_16804\1732683939.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(s1.append(s2))


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [ ]:
# YOUR CODE HERE