## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [263]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

YOUR ANSWER HERE

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE

a = np.array([1,2,3,4,5,6,7,8,9,0])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [6]:
# YOUR CODE HERE

a = np.zeros((10,10), dtype=int)

print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [10]:
# YOUR CODE HERE

a = np.ones((10,10), dtype=float)

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [21]:
# YOUR CODE HERE

a = np.full((10,10), 9, dtype=int)

print(a)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [22]:
# YOUR CODE HERE

l = (range(5,26,3))

a = np.array(l)

print(a)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [23]:
# YOUR CODE HERE

a = np.linspace(-1,1,30)

print(a)



[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [38]:
# YOUR CODE HERE

m = np.arange(0,30).reshape(5,6)

print(m)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [52]:
# YOUR CODE HERE

a = np.random.randint(0,100,30)
print(a,'\n')
print(np.sort(a))

[10 91 56 88 49 22 30 93 41 98  6 15 89 59  1  0 47 11 68 36 31  8 98 18
 47 79  2 19 23 53] 

[ 0  1  2  6  8 10 11 15 18 19 22 23 30 31 36 41 47 47 49 53 56 59 68 79
 88 89 91 93 98 98]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [58]:
# YOUR CODE HERE

m = np.ones((5,10))

print(m, '\n')
print('Number of elements :',m.size, '\n')
print('Shape of the matrix:',m.shape, '\n')
print('The Data type is   :',m.dtype, '\n')

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

Number of elements : 50 

Shape of the matrix: (5, 10) 

The Data type is   : float64 



11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [66]:
# YOUR CODE HERE

m = np.random.randint(11, size=(3, 4,7))

print(m)

[[[ 2  6 10 10  1  8  9]
  [ 9  0  5  6  7  9  8]
  [ 1 10  9  1  4  4  5]
  [ 2  7  0  5  3  0  6]]

 [[ 8  3  3  5  2  5  6]
  [10  9  9  2  6  2  1]
  [ 9  3  7  8  6  0  2]
  [ 8  0  8  7  0  5  4]]

 [[ 5  9  4  5  4 10  4]
  [ 3  2  2  3  8  1  8]
  [ 0  0  4  5  5  2  6]
  [ 8 10  9  7  5  7  4]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [79]:
# YOUR CODE HERE

a = np.random.randint(0,20,20)

print(a,'\n')
print(a.reshape(4,5))


[ 4  3  9 16  9 16 19  4  1  5  1 12 10 10 15 10 18 14 15 10] 

[[ 4  3  9 16  9]
 [16 19  4  1  5]
 [ 1 12 10 10 15]
 [10 18 14 15 10]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [81]:
# YOUR CODE HERE

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])
a4 = np.array([10, 11, 12])
r = np.concatenate((a1, a2, a3, a4))
print(r,'\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [110]:
# YOUR CODE HERE

a1 = np.random.randint(0, 16,3).reshape(3,1)

a2 = np.random.randint(0, 32,(3, 3))

print('Vector of length 3 :\n',a1,'\n')
print('Matrix of size 3x3 :\n',a2,'\n')
m = np.column_stack((a1,a2))
print('Combine these two arrays :\n', m)

Vector of length 3 :
 [[12]
 [ 7]
 [13]] 

Matrix of size 3x3 :
 [[17 24  0]
 [14  7 27]
 [10 11 11]] 

Combine these two arrays :
 [[12 17 24  0]
 [ 7 14  7 27]
 [13 10 11 11]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

#### "axis = 0" means that the operation will be performed along the rows of the array.
#### "axis = 1" means that the operation will be performed along the columns of the array.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [122]:
# YOUR CODE HERE

a1 = np.arange(0, 19)

print(a1[3:8:2])



[3 5 7]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [142]:
# YOUR CODE HERE

a = np.random.randint(10,20,10)

print(a,'\n')
a[3] = 7
print(a,'\n\nThe 4th element of this array was replaced to "7"')

[18 16 10 17 12 17 14 10 16 14] 

[18 16 10  7 12 17 14 10 16 14] 

The 4th element of this array was replaced to "7"


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


#### - A diagonal matrix is a special kind of square matrix whose entries are zero everywhere except for the main diagonal, which runs from the upper left corner to the lower right corner.

#### - A trace of a square matrix is the sum of its diagonal elements. In other words, it is the sum of the elements on the main diagonal of the matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [282]:
# YOUR CODE HERE

g = np.array([[15, 0, 0], [0, 16, 0], [0, 0, 32]])

print(g,'\n')
print('The indexes of the diagonal are:','\n', g[0,0],g[1,1],g[2,2],'\n')
print('The trace is:',np.trace(g))

[[15  0  0]
 [ 0 16  0]
 [ 0  0 32]] 

The indexes of the diagonal are: 
 15 16 32 

The trace is: 63


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [161]:
# YOUR CODE HERE

a = np.arange(10,21)

print(a,'\n')
print('The index to 3rd to the last index are:','\n', a[2:],'\n')

[10 11 12 13 14 15 16 17 18 19 20] 

The index to 3rd to the last index are: 
 [12 13 14 15 16 17 18 19 20] 



21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [181]:
# YOUR CODE HERE

a = np.random.randint(0, 100,(10, 10))

print(a,'\n')
print(a[3][5],'\n')
print(a[:,5],'\n')
print(a[2,:],'\n')
print(a[2:7,:],'\n')
print(a[2:5,3:7],'\n')
print(a[5:, :4],'\n')
a[4,4] = 1989
print(a,'\n')

[[83 44 70 77 62 72 18 46 13 37]
 [52 60 35 39 80 29  8 63 32 51]
 [88 13 74 52 98 58 77 93 40 67]
 [67 91  7  1 85 40 54 15 92 61]
 [47 29 11 34 10 63 49 84 20 68]
 [47 19 66 43 32 72 60  8 67 34]
 [80 97 87 95 64  7 44 86 46 39]
 [75 53 75 45 46 14 18 25 51 92]
 [21 20 50 37 19 28 50  3 54 70]
 [91 27  3 21 75 44 66 85 65 87]] 

40 

[72 29 58 40 63 72  7 14 28 44] 

[88 13 74 52 98 58 77 93 40 67] 

[[88 13 74 52 98 58 77 93 40 67]
 [67 91  7  1 85 40 54 15 92 61]
 [47 29 11 34 10 63 49 84 20 68]
 [47 19 66 43 32 72 60  8 67 34]
 [80 97 87 95 64  7 44 86 46 39]] 

[[52 98 58 77]
 [ 1 85 40 54]
 [34 10 63 49]] 

[[47 19 66 43]
 [80 97 87 95]
 [75 53 75 45]
 [21 20 50 37]
 [91 27  3 21]] 

[[  83   44   70   77   62   72   18   46   13   37]
 [  52   60   35   39   80   29    8   63   32   51]
 [  88   13   74   52   98   58   77   93   40   67]
 [  67   91    7    1   85   40   54   15   92   61]
 [  47   29   11   34 1989   63   49   84   20   68]
 [  47   19   66   43   32   72   6

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [211]:
# YOUR CODE HERE

a = np.arange(0,55,5)

print('The array from 0 to 50 jumping with steps:\n',a,'\n')
print('The values greater than 20 are:\n',a[a > 20],'\n')
print('The values less than 30 are:\n',a[a < 30],'\n',)
print('The values are 33 :\n',np.count_nonzero(a == 33),'\n')
print('Array multiplied by 5:\n',a *5 ,'\n')

The array from 0 to 50 jumping with steps:
 [ 0  5 10 15 20 25 30 35 40 45 50] 

The values greater than 20 are:
 [25 30 35 40 45 50] 

The values less than 30 are:
 [ 0  5 10 15 20 25] 

The values are 33 :
 0 

Array multiplied by 5:
 [  0  25  50  75 100 125 150 175 200 225 250] 



23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [214]:
# YOUR CODE HERE

a = np.random.rand((50))
print('The array of 50 ramdom floats between 0 and 1:\n \n',a,'\n')
print('The average is: \n',a.mean(),'\n')
print('The variance is:\n',a.var(),'\n')
print('The smallest value is:\n',a.min(),'\n')
print('The largest value is:\n',a.max(),'\n')

The array of 50 ramdom floats between 0 and 1:
 
 [0.42870202 0.02916976 0.48089015 0.66243401 0.11850262 0.28888494
 0.39783663 0.91953102 0.99325502 0.0449113  0.76100792 0.37172407
 0.39245819 0.75426497 0.91842643 0.95092859 0.57712259 0.35712116
 0.78754909 0.25100138 0.56407403 0.35857846 0.65663107 0.24039891
 0.19159295 0.91823909 0.10180368 0.50595791 0.22085278 0.03892996
 0.03601882 0.17522177 0.86677035 0.28247874 0.95045917 0.58162229
 0.43661419 0.58008883 0.51669839 0.75877625 0.28249607 0.35305039
 0.8940943  0.94645651 0.89255823 0.41944799 0.7803655  0.47633573
 0.49753985 0.20468011] 

The average is: 
 0.5042910843004741 

The variance is:
 0.08330693590610988 

The smallest value is:
 0.029169763645264468 

The largest value is:
 0.993255015422964 



24. What are the differences between Pandas Series and NumPy arrays?

#### A Pandas Series has an explicit index associated with the values, while a NumPy array has an implicit index that is determined by the array's position in memor

#### NumPy arrays support a wide range of data types (e.g. integers, floats, booleans, etc.), while Pandas Series are typically used for storing a single data type (e.g. integers, floats, or strings).

25. Create a 5-element series with different data types, with an index of capital letters.

In [216]:
# YOUR CODE HERE

s = pd.Series([1,2,3,4,5], index=['A','B', 'C','D','E'])

print(s)

A    1
B    2
C    3
D    4
E    5
dtype: int64


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [225]:
# YOUR CODE HERE

d = {'Barcelona':'Spain','Istambul':'Turkey','New York':'USA','Berlin':'Germany','Amsterdam':'Netherlands'}
print(pd.Series(d))

Barcelona          Spain
Istambul          Turkey
New York             USA
Berlin           Germany
Amsterdam    Netherlands
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [244]:
# YOUR CODE HERE

a = np.random.randint(1,10,10)

s = pd.Series(a,index=['a','b','c','d','e','f','g','h','i','j'])
print('The vector is :\n \n',a,'\n')
print('The vector to series: \n',s,'\n')
print('The 3rd element using the index name "c": \n',s['c'],'\n')
print('The 3rd element using the index number "[1]:" \n',s[0],'\n')
print('The 2nd and 7th elements using the index name "b & g:" \n',s[['b','g']],'\n')

The vector is :
 
 [6 8 1 2 9 3 6 5 2 7] 

The vector to series: 
 a    6
b    8
c    1
d    2
e    9
f    3
g    6
h    5
i    2
j    7
dtype: int32 

The 3rd element using the index name "c": 
 1 

The 3rd element using the index number "[1]:" 
 6 

The 2nd and 7th elements using the index name "b & g:" 
 b    8
g    6
dtype: int32 



28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [250]:
# YOUR CODE HERE

s1 = pd.Series(['A','B','C','D','E',])
s2 = pd.Series(['f','g','h','i','j'])
s3 = pd.concat([s1,s2])
print(s3,'\n')

s3.index = range(1,11)

print(s3,'\n')

0    A
1    B
2    C
3    D
4    E
0    f
1    g
2    h
3    i
4    j
dtype: object 

1     A
2     B
3     C
4     D
5     E
6     f
7     g
8     h
9     i
10    j
dtype: object 



**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [280]:
# YOUR CODE HERE

import time

tim = time.time()
n = 20

# Create two random matrices
m1 = np.random.random((n,n))
m2 = np.random.random((n,n))


cont = 0

while True:
    
    cont += 1
    
    m_dif = m1 - m2
    diag = np.diag(m_dif)
    
    if all(np.abs(diag) <= 0.1):
        break
   
    m1 = np.random.random((n,n))
    m2 = np.random.random((n,n))

print("Number of cycles: ", cont)
print("Time taken: ", time.time() - tim)
print("Matrix: \n", m_dif)


Number of cycles:  615
Time taken:  0.046007394790649414
Matrix: 
 [[ 5.12960497e-02  1.50895550e-01  5.31729811e-01  6.85444455e-01
   4.91517525e-01]
 [ 3.21457365e-01  2.32746902e-02 -6.98088721e-01  4.58002488e-01
   4.51868608e-02]
 [ 4.13905849e-01 -1.38195570e-01  8.19292213e-02 -8.21630987e-01
  -4.56649574e-01]
 [-8.55747027e-02  2.26607804e-01  7.00156052e-01 -8.84234895e-03
  -5.91992870e-01]
 [ 1.63624510e-01 -5.93161842e-01 -1.58079524e-01  5.53934336e-01
   2.17963615e-04]]
