## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is an array with a single dimension, while a matrix refers to an array with two dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
list1 = [0,1,2,3,4,5,6,7,8,9]
array1 = np.array(list1)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [5]:
array3 = np.zeros((10,10), dtype=int)
array3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [8]:
array4 = np.ones((10,10))
array4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [10]:
array5 = np.ones((10,10), dtype = int) * 9
array5

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [25]:
array6 = np.arange(5, 25, 3)
array6

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [26]:
array7 = np.linspace(-1,1,30)
array7

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [48]:
array8 = np.arange(0,30).reshape((5,6))
array8

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [34]:
array9  = np.sort(np.random.randint(0,100,30))
array9

array([ 1,  2,  3,  6,  8, 13, 14, 17, 20, 38, 41, 46, 50, 50, 52, 54, 59,
       59, 59, 61, 61, 61, 63, 72, 79, 83, 88, 89, 91, 91])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [41]:
array10 = np.ones((5,10), dtype = int)
print("Array", array10)
print("number of elements: ", array10.size)
print("shape of the matrix: ", array10.shape)
print("the data type of the matrix: ", array10.dtype)

Array [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
number of elements:  50
shape of the matrix:  (5, 10)
the data type of the matrix:  int32


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [49]:
matrix11 = np.random.randint(0,10,(3,4,7))
matrix11

array([[[2, 5, 1, 9, 8, 4, 5],
        [3, 9, 6, 8, 6, 0, 0],
        [8, 8, 3, 8, 2, 6, 5],
        [7, 8, 4, 0, 2, 9, 7]],

       [[5, 7, 8, 3, 0, 0, 9],
        [3, 6, 1, 2, 0, 4, 0],
        [7, 0, 0, 1, 1, 5, 6],
        [4, 0, 0, 2, 1, 4, 9]],

       [[5, 6, 3, 6, 7, 0, 5],
        [7, 4, 3, 1, 5, 5, 0],
        [8, 5, 2, 3, 3, 2, 9],
        [2, 2, 3, 6, 3, 8, 0]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [51]:
array12 = np.random.randint(0,100,20)
array12.reshape(4,5)

array([[47, 11, 68, 36, 31],
       [ 8, 98, 18, 47, 79],
       [ 2, 19, 23, 53, 32],
       [23, 74, 71, 35, 37]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [62]:
array1 =  np.arange(0,5)
array2 = np.arange(5,10)
array3 = np.arange(10,15)
array4 = np.arange(15,20)
array_sum = np.concatenate([array1, array2, array3, array4])
array_sum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [74]:
vector = np.random.randint(0,20,(3,1))
print(vector)
matrix = np.random.randint(0,20,(3,3))
print(matrix)
print(np.concatenate([matrix, vector], axis = 1))


[[11]
 [17]
 [ 2]]
[[ 0  0 18]
 [10  4 11]
 [ 2  0  0]]
[[ 0  0 18 11]
 [10  4 11 17]
 [ 2  0  0  2]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

If "axis=0", Numpy performs the action on elements of each column, and if "axis=1", it performs the action on rows.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [77]:
vector = np.random.randint(0,30,20)
print(vector)
print(vector[2:7:2])

[ 9  4  8 23  2 16  2 15  3 17 16  6 23 22 29  4 11 16 22 12]
[8 2 2]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [82]:
vector = np.random.randint(0,30,10)
print(vector)
vector[3] = 40
print(vector)

[20 22 15 24  6 12 20  9 25  6]
[20 22 15 40  6 12 20  9 25  6]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero.
The trace of a square matrix is the sum of its diagonal entries.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [84]:
dmatrix = np.array([[5, 0, 0], [0, 6, 0], [0, 0, 8]])

print(dmatrix,'\n')
print('The indexes of the diagonal are:','\n', dmatrix[0,0],dmatrix[1,1],dmatrix[2,2],'\n')

[[5 0 0]
 [0 6 0]
 [0 0 8]] 

The indexes of the diagonal are: 
 5 6 8 



20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [89]:
vector = np.arange(10,21)
print(vector[2::])

[12 13 14 15 16 17 18 19 20]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [108]:
matrix21 = np.random.randint(1,100,(10,10))
print(matrix21)

[[ 2 70 17 89 28 66 35  5 65 40]
 [76 56 36 45 23 47 31 11 10 67]
 [14 80 74 93 10 76 94  1  5 20]
 [ 8 43 76  1 57 64 84 28 37 47]
 [76 37 49 44 56 28 79  6 61 20]
 [78  2 73 37 20 26 29  1 35 70]
 [59 69 33 51 78 12 20 53 88 43]
 [98 89 50 29 57 39 95 56 43 50]
 [23 44 38 84 23 45 52 80 50  8]
 [85  1  8 29 96  5 86 47 34 65]]


In [109]:
print(matrix21[2,4]) #column 5 of row 3
print(matrix21[:,4]) #all elements of column 5
print(matrix21[1,:]) #the 2nd row of all columns
print(matrix21[1:7,:]) #row 2 through 7 of all columns.
print(matrix21[2:6,3:8]) #row index 2 to 5 and column index 3 to 7
print(matrix21[5:,:5]) #rom row index 5 to the end and column index from the top to 4
matrix21[4,4] = 1984 #corresponding to the 5th row and the 5th column with your year of birth
print(matrix21)

10
[28 23 10 57 56 20 78 57 23 96]
[76 56 36 45 23 47 31 11 10 67]
[[76 56 36 45 23 47 31 11 10 67]
 [14 80 74 93 10 76 94  1  5 20]
 [ 8 43 76  1 57 64 84 28 37 47]
 [76 37 49 44 56 28 79  6 61 20]
 [78  2 73 37 20 26 29  1 35 70]
 [59 69 33 51 78 12 20 53 88 43]]
[[93 10 76 94  1]
 [ 1 57 64 84 28]
 [44 56 28 79  6]
 [37 20 26 29  1]]
[[78  2 73 37 20]
 [59 69 33 51 78]
 [98 89 50 29 57]
 [23 44 38 84 23]
 [85  1  8 29 96]]
[[   2   70   17   89   28   66   35    5   65   40]
 [  76   56   36   45   23   47   31   11   10   67]
 [  14   80   74   93   10   76   94    1    5   20]
 [   8   43   76    1   57   64   84   28   37   47]
 [  76   37   49   44 1984   28   79    6   61   20]
 [  78    2   73   37   20   26   29    1   35   70]
 [  59   69   33   51   78   12   20   53   88   43]
 [  98   89   50   29   57   39   95   56   43   50]
 [  23   44   38   84   23   45   52   80   50    8]
 [  85    1    8   29   96    5   86   47   34   65]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [126]:
x = np.arange(5,51, 5) 
print(x)
print(x[x>20])
print(x[x<30])
print(x[x==33].size)
print(x*5)

[ 5 10 15 20 25 30 35 40 45 50]
[25 30 35 40 45 50]
[ 5 10 15 20 25]
0
[ 25  50  75 100 125 150 175 200 225 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [9]:
x = np.random.rand(50)
print(x)
print(x.mean())
print(x.std())
print(x.var())
print(np.median(x))
print(x.min())
print(x.max())

[0.0754149  0.6809908  0.51557131 0.04573999 0.46411969 0.34351093
 0.51606012 0.883321   0.46030827 0.19535261 0.75842801 0.65112369
 0.7298361  0.09647493 0.75980069 0.09360817 0.31722363 0.80279456
 0.29425982 0.0799367  0.68161396 0.46682991 0.07825015 0.60443948
 0.56487677 0.16600446 0.44826654 0.05471213 0.81998168 0.35580556
 0.15670478 0.22450953 0.02681961 0.67236954 0.45154574 0.16262797
 0.74198999 0.75792781 0.10424258 0.20996269 0.29834975 0.51092205
 0.82551075 0.65913408 0.04047565 0.63522513 0.61578304 0.25560785
 0.14488366 0.92728709]
0.42853071681408894
0.271618827947669
0.07377678769566541
0.4559270031978923
0.02681961499427976
0.9272870882744719


24. What are the differences between Pandas Series and NumPy arrays?


*The Pandas Series has an explicit index definition, which gives it additional capabilities compared to the numpy array.
*The indices of a Pandas Series must not be of an integer data type, but they can take other data types like strings.  They can also be non-sequential or non-contiguous.
*Operations between Series objects automatically align data based on the label during alignment.
*If no matching labels are found, Pandas returns NaN.
*Pandas does a lot of work during indexing, hence, it is faster to index numpy arrays than Pandas Series objects.

25. Create a 5-element series with different data types, with an index of capital letters.

In [133]:
x = pd.Series([10, "Ali", 5.2, True, [1,3]], index = ["A", "B", "C", "D", "E"])
x

A        10
B       Ali
C       5.2
D      True
E    [1, 3]
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [136]:
x = {"France" : "Paris" , "Turkey" : "Ankara", "Belgium" : "Brussels", "Germany" : "Berlin", "Greece" : "Athens"}
print(pd.Series(x))


France        Paris
Turkey       Ankara
Belgium    Brussels
Germany      Berlin
Greece       Athens
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indexes. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [145]:
x = np.random.randint(0, 10, 10)
series = pd.Series(x, index=["a","b","c","d","e","f","g","h","i","j"])
print(series)
print(series["c"])
print(series[0])
print(series[["b","g"]])

a    3
b    3
c    1
d    5
e    1
f    6
g    2
h    2
i    4
j    2
dtype: int32
1
3
b    3
g    2
dtype: int32


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [5]:
series1 = pd.Series([1,3,5,7,9])
series2 = pd.Series([2,4,6,8,10])
series3 = pd.concat([series1, series2])
print(series3, "/n")
series3.index = range(1,11)
print(series3)

0     1
1     3
2     5
3     7
4     9
0     2
1     4
2     6
3     8
4    10
dtype: int64 /n
1      1
2      3
3      5
4      7
5      9
6      2
7      4
8      6
9      8
10    10
dtype: int64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [10]:
import time
starting_point = time.time()
cycles = 0
while True:
    difference = np.random.rand(5, 5) - np.random.rand(5, 5)
    diagonal = np.diag(difference)
    if (diagonal < 0.1).all() and (diagonal > -0.1).all():
        end_point = time.time()
        break
    cycles+=1
    
print("Number of cycles: ", cycles)
print("Time it took: ", end_point - starting_point)
print("The matrix is:", diagonal)

Number of cycles:  1422
Time it took:  0.04361081123352051
The matrix is: [ 0.08300426 -0.02146558 -0.08756111  0.04831588  0.02658586]
