## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 18-01 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is an array with a single dimension, while a matrix refers to an array with two or more dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [2]:
list = [1,2,3,4,5,6,7,8,9,10]
a = np.array(list)

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [3]:
a = np.zeros([10, 10], dtype = int)

4. Construct a 10x10 matrix filled with '1's, data type float.

In [4]:
a = np.ones([10, 10], dtype = float)

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [5]:
a= np.full((10,10),9, dtype=int)
print(a)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [6]:
a = np.arange(5, 25, 3)
print(a)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [7]:
a = np.linspace(-1, 1, 30)
print(a)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [8]:
a = np.random.randint(0,30,size=(5,6))
print(a)

[[ 6 19 28 14 10  7]
 [28 20  6 25 18 22]
 [10 10 23 20  3  7]
 [23  2 21 20  1 23]
 [11 29  5  1 27 20]]


9. Create an array of 30 random integers and sort it in ascending order.

In [9]:
a = np.random.randint(100,size=(1,30))
a= np.sort(a)
print(a)

[[ 2  3  6 14 17 20 21 32 38 41 46 48 50 50 54 57 58 59 59 61 61 61 63 72
  75 79 88 88 90 91]]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [10]:
a = np.ones([5, 10], dtype = int)
print(a)
print(a.size)
print(a.shape)
print(a.dtype)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
50
(5, 10)
int32


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [11]:
a = np.random.randint(10,size=(3,4,7))
print(a)

[[[1 9 8 9 4 1 3]
  [6 7 2 0 3 1 7]
  [3 1 5 5 9 3 5]
  [1 9 1 9 3 7 6]]

 [[8 7 4 1 4 7 9]
  [8 8 0 8 6 8 7]
  [0 7 7 2 0 7 2]
  [2 0 4 9 6 9 8]]

 [[6 8 7 1 0 6 6]
  [7 4 2 7 5 2 0]
  [2 4 2 0 4 9 6]
  [6 8 9 9 2 6 0]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [12]:
a = np.random.randint(0, 100, size=20)
my_matrix = a.reshape(4, 5)
print(my_matrix)

[[51 95  3 93 22]
 [14 42 28 35 12]
 [31 70 58 85 27]
 [65 41 44 61 56]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [13]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.array([7, 8, 9])
array_4 = np.array([10, 11, 12])
a = np.concatenate((array_1, array_2, array_3, array_4))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [14]:
vector = np.array([1, 2, 3]).reshape(3,1)
matrix = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
a = np.column_stack((vector, matrix))
print(a)

[[ 1  4  5  6]
 [ 2  7  8  9]
 [ 3 10 11 12]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

In Numpy, the axis parameter is used to specify along which axis the operation should be performed.

axis=0 refers to the rows of the array, so the operation will be performed vertically across the rows.
axis=1 refers to the columns of the array, so the operation will be performed horizontally across the columns.
For example, if you have a 2D array and you want to sum the values in each column, you would set axis=0. If you want to sum the values in each row, you would set axis=1.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [15]:
a = np.random.rand(20)
print(a)
print(a[2],a[4],a[6])

[1.05494260e-01 4.56534570e-01 2.18440437e-01 4.16509948e-01
 8.83280259e-01 3.24345021e-01 1.22087955e-01 3.56297838e-01
 9.06828442e-01 2.72132249e-01 6.47690121e-01 5.20376995e-04
 3.52568856e-01 3.04781258e-01 1.64655853e-01 5.34089419e-01
 4.84829971e-01 6.92436033e-01 2.69412334e-01 2.44125522e-01]
0.2184404372168336 0.8832802589188683 0.12208795470067335


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [16]:
a = np.random.rand(10)
a[3]= 77
print(a)

[1.68291042e-01 2.18764220e-01 5.58102002e-01 7.70000000e+01
 6.48922471e-02 2.53915414e-01 2.46876063e-01 6.96304273e-01
 7.12270590e-01 1.48086930e-01]


18. Look up the concepts of diagonal matrix and trace matrix online and write a small explanation about what they are.

A diagonal matrix is a square matrix in which all the entries outside the main diagonal are zero. The main diagonal of a matrix is the diagonal running from the top left corner to the bottom right corner. The entries on the main diagonal are known as the diagonal entries of the matrix.

A trace of a square matrix is the sum of its diagonal entries. The trace of a matrix is denoted by the notation tr(A) or trace(A). The trace of a matrix is a scalar value and it is a measure of the amount of "diagonalness" in the matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [19]:
a = np.diag([1, 2, 3, 4, 5])
print(a)
#The indexes of the iagonal are (0,0), (1,1), (2,2), (3,3),and (4,4)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [ ]:
a= np.arange(10, 21)
print(a[2:])

[12 13 14 15 16 17 18 19 20]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [ ]:
a = np.random.rand(10,10)
print(a)
print(a[2,4])
print(a[:,4])
print(a[1,:])
print(a[2:7,:])
print(a[1:4,2:6])
print(a[4:, :3])
a[4,4]= 1983

[[0.78151448 0.82794089 0.75050192 0.79953713 0.82513268 0.18640499
  0.23569175 0.63375856 0.90786613 0.31619658]
 [0.58830668 0.68298206 0.4519486  0.71378245 0.89966745 0.62410154
  0.53978106 0.43874468 0.57748627 0.35536245]
 [0.39148211 0.53185748 0.06661911 0.22902539 0.54284931 0.43152814
  0.33281579 0.73054914 0.69371761 0.16673076]
 [0.87862912 0.49542363 0.74146091 0.57315085 0.99769262 0.75240312
  0.70698046 0.77857194 0.14312799 0.20454459]
 [0.71406408 0.49398149 0.75463529 0.10291603 0.53648135 0.37882157
  0.45700022 0.60395787 0.50228835 0.53986064]
 [0.48635748 0.40895518 0.77188198 0.01220307 0.5984427  0.56550835
  0.71617907 0.59902936 0.82679883 0.95907479]
 [0.34252426 0.22735098 0.42359686 0.28792962 0.61495026 0.91185241
  0.13911619 0.1007946  0.25601553 0.72609559]
 [0.59296291 0.10221266 0.91875052 0.79008464 0.0230226  0.65136721
  0.77124667 0.37443537 0.06892154 0.07732107]
 [0.10424697 0.84043963 0.9106862  0.12281078 0.23590603 0.16552051
  0.18632088

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [ ]:
a = np.arange(0, 55, 5)

# Print all values greater than 20
print(a[a > 20])

# Print all values less than 30
print(a[a < 30])

# How many values are 33 in it?
print(np.count_nonzero(a==33))

# Multiply all the elements of the created a by 5.
a *= 5
print(a)

[25 30 35 40 45 50]
[ 0  5 10 15 20 25]
0
[  0  25  50  75 100 125 150 175 200 225 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [ ]:
a = np.random.rand(50)

# Take the average
average = np.average(a)
print(average)

# Get the standard deviation
std_dev = np.std(a)
print(std_dev)

# Get the variance
variance = np.var(a)
print(variance)

# Take the median
median = np.median(a)
print(median)

# Find the smallest value
smallest = np.min(a)
print(smallest)

# Find the largest value
largest = np.max(a)
print(largest)

24. What are the differences between Pandas Series and NumPy arrays?

Pandas Series and NumPy arrays are both used for data manipulation and analysis in Python, but they have some key differences:

Indexing: A Pandas Series has an explicit index, which means that each element in the Series has a label or name associated with it. A NumPy array, on the other hand, has an implicit index, which means that the elements are accessed by their integer position.

Data types: A Pandas Series can hold data of different types, such as integers, strings, and dates. A NumPy array, on the other hand, can only hold data of the same type, such as integers or floating-point numbers.

Missing values: Pandas Series can handle missing values, represented by the special value NaN. NumPy arrays do not have native support for missing values.

Functionality: Pandas has many built-in functions for data manipulation, such as groupby, merge, and pivot_table, which are not present in NumPy arrays. Also Pandas is built on top of NumPy so it can use all the functionality of NumPy and more.

Memory usage: Pandas Series and Dataframe use more memory than NumPy arrays because they have additional metadata, such as the index and column labels.

25. Create a 5-element series with different data types, with an index of capital letters.

In [ ]:
data = {'A': 1, 'B': 'Hello', 'C': 3.14, 'D': [1, 2, 3], 'E': True}

# create a series
series = pd.Series(data)

# print the series
print(series)

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [ ]:
data = {'france': 'paris', 'Yemen': 'Sanaa', 'Netherland': 'Amsterdam', 'UK': 'London', 'Turkey': 'Ankara'}
# create a series
series = pd.Series(data)

# print the series
print(series)

france            paris
Yemen             Sanaa
Netherland    Amsterdam
UK               London
Turkey           Ankara
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [23]:
# create a random vector with 10 elements
vector = np.random.rand(10)

# convert the vector to a series and set string indices
indices = ['a','b','c','d','e','f','g','h','i','j']
series = pd.Series(vector, index=indices)

# Retrieve the 3rd element of the series using the index name
print(series['c'])

# Retrieve the 1st element of the series using the index number
print(series[0])

# Access the 2nd and 7th elements of the series at the same time, using the index name
print(series[['b', 'g']])

0.9366284872121639
0.9249099859493469
0.9249099859493469
b    0.700046
g    0.989550
dtype: float64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [25]:
s1 = pd.Series([10, 20, 30, 40, 50])

s2 = pd.Series([60, 70, 80, 90, 100])

print(s1.append(s2, ignore_index=True))

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64


C:\Users\Niyazi Al Ashwal\AppData\Local\Temp\ipykernel_20520\222723057.py:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(s1.append(s2, ignore_index=True))


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [18]:

import time

# starting time
start_time = time.time()

# initialize the number of cycles
n_cycles = 0

# generate the matrices and take the difference
while True:
    n_cycles += 1
    matrix1 = np.random.rand(20, 20)
    matrix2 = np.random.rand(20, 20)
    diff_matrix = matrix1 - matrix2
    diag = np.diag(diff_matrix)
    if all(-0.1 <= i <= 0.1 for i in diag):
        break

# ending time
end_time = time.time()

# print the results
print("Total number of cycles:", n_cycles)
print("Total time taken: {:.4f} seconds".format(end_time - start_time))
print("Desired matrix:")
print(diff_matrix)







KeyboardInterrupt: 